name: linting-pipeline
on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  linting-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create package.json
        run: npm init -y

      - name: Install dependencies
        run: npm install --save-dev htmlhint 
      - name: Install other dependencies
        run : npm install --save-dev stylelint

      - name: Run HtmlHint
        run: npx htmlhint "**/*.html"

      - name: Run Stylelint
        run: npx stylelint "**/.css"
